# Generated by Django 5.1.6 on 2025-02-28 15:46

import django.core.validators
import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(validators=[students.models.validate_birth_date])),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato: "+999999999". Até 15 dígitos são permitidos.', regex='^\\+?1?\\d{9,15}$')])),
                ('street', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('number', models.CharField(default='S/N', max_length=6)),
                ('block', models.CharField(default='S/Q', max_length=6)),
                ('city', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('XX', 'Outro')], help_text='Selecione o estado brasileiro', max_length=2)),
                ('zip_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='O CEP deve conter 8 dígitos numéricos, sem traços ou pontos.', regex='^\\d{8}$')])),
                ('country', models.CharField(default='Brasil', max_length=255)),
                ('channel', models.CharField(choices=[('I', 'Instagram'), ('F', 'Indicação'), ('Y', 'Youtube'), ('S', 'Site'), ('A', 'Anuncio'), ('E', 'Embaixador'), ('P', 'Professor'), ('V', 'Prospeccao'), ('X', 'Outro')], max_length=1)),
                ('other_channel', models.CharField(blank=True, max_length=30, null=True)),
                ('desired_course', models.CharField(choices=[('C', 'Ciência da Computação'), ('P', 'CFO - Curso de Formação de Oficiais'), ('D', 'Direito'), ('F', 'Enfermagem'), ('E', 'Engenharia Civil'), ('M', 'Medicina'), ('V', 'Medicina Veterinária'), ('O', 'Odontologia'), ('X', 'Outro')], max_length=1)),
                ('other_desired_course', models.CharField(blank=True, max_length=30, null=True)),
                ('observations', models.TextField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'student',
            },
        ),
    ]
